// Initial realistic mock data for Healthcare Appointment Capacity & Queue Management Platform
// Used as fallback when Spring Boot backend APIs are connecting or in offline mode

export const initialDepartments = [
  { id: 1, code: 'CARD', name: 'Cardiology', description: 'Heart and cardiovascular system care', headDoctor: 'Dr. Priya Sharma', activeDoctors: 4, dailyCapacity: 60 },
  { id: 2, code: 'ORTH', name: 'Orthopedics', description: 'Bone, joint, and musculoskeletal disorders', headDoctor: 'Dr. Arvind Patel', activeDoctors: 3, dailyCapacity: 45 },
  { id: 3, code: 'NEUR', name: 'Neurology', description: 'Brain and nervous system diagnostics', headDoctor: 'Dr. Rajesh Nair', activeDoctors: 2, dailyCapacity: 30 },
  { id: 4, code: 'PEDI', name: 'Pediatrics', description: 'Comprehensive child healthcare', headDoctor: 'Dr. Ananya Sen', activeDoctors: 3, dailyCapacity: 50 },
  { id: 5, code: 'GENM', name: 'General Medicine', description: 'Primary health consultations and routine care', headDoctor: 'Dr. Vikram Verma', activeDoctors: 5, dailyCapacity: 80 },
  { id: 6, code: 'DERM', name: 'Dermatology', description: 'Skin, hair, and nail health', headDoctor: 'Dr. Sneha Kulkarni', activeDoctors: 2, dailyCapacity: 35 },
];

export const initialDoctors = [
  {
    id: 1,
    name: 'Dr. Priya Sharma',
    email: 'priya.sharma@hospital.org',
    phone: '+91 98765 43210',
    departmentId: 1,
    departmentName: 'Cardiology',
    specialization: 'Senior Interventional Cardiologist',
    roomNumber: 'OPD-102',
    maxPatientsPerDay: 25,
    slotDurationMinutes: 30,
    status: 'ACTIVE',
    rating: 4.9,
    experienceYears: 14,
  },
  {
    id: 2,
    name: 'Dr. Arvind Patel',
    email: 'arvind.patel@hospital.org',
    phone: '+91 98765 43211',
    departmentId: 2,
    departmentName: 'Orthopedics',
    specialization: 'Joint Replacement & Arthroscopy Specialist',
    roomNumber: 'OPD-204',
    maxPatientsPerDay: 20,
    slotDurationMinutes: 30,
    status: 'ACTIVE',
    rating: 4.8,
    experienceYears: 12,
  },
  {
    id: 3,
    name: 'Dr. Rajesh Nair',
    email: 'rajesh.nair@hospital.org',
    phone: '+91 98765 43212',
    departmentId: 3,
    departmentName: 'Neurology',
    specialization: 'Consultant Neuro-physician',
    roomNumber: 'OPD-305',
    maxPatientsPerDay: 15,
    slotDurationMinutes: 45,
    status: 'ACTIVE',
    rating: 4.9,
    experienceYears: 18,
  },
  {
    id: 4,
    name: 'Dr. Ananya Sen',
    email: 'ananya.sen@hospital.org',
    phone: '+91 98765 43213',
    departmentId: 4,
    departmentName: 'Pediatrics',
    specialization: 'Consultant Pediatrician & Neonatologist',
    roomNumber: 'OPD-110',
    maxPatientsPerDay: 30,
    slotDurationMinutes: 20,
    status: 'ACTIVE',
    rating: 4.7,
    experienceYears: 9,
  },
  {
    id: 5,
    name: 'Dr. Vikram Verma',
    email: 'vikram.verma@hospital.org',
    phone: '+91 98765 43214',
    departmentId: 5,
    departmentName: 'General Medicine',
    specialization: 'Internal Medicine Specialist',
    roomNumber: 'OPD-101',
    maxPatientsPerDay: 35,
    slotDurationMinutes: 15,
    status: 'ACTIVE',
    rating: 4.6,
    experienceYears: 15,
  },
];

export const initialPatients = [
  {
    id: 1,
    patientNumber: 'MED-2026-001',
    name: 'Ramesh Kumar',
    age: 48,
    gender: 'MALE',
    phone: '+91 98111 22334',
    email: 'ramesh.k@gmail.com',
    bloodGroup: 'B+',
    address: 'B-42 Indira Nagar, Bangalore',
    allergies: 'Penicillin',
    registeredDate: '2026-01-15',
  },
  {
    id: 2,
    patientNumber: 'MED-2026-002',
    name: 'Meena Devi',
    age: 62,
    gender: 'FEMALE',
    phone: '+91 98222 33445',
    email: 'meenadevi62@yahoo.com',
    bloodGroup: 'O+',
    address: '77 Malleshwaram, Bangalore',
    allergies: 'None',
    registeredDate: '2026-02-10',
  },
  {
    id: 3,
    patientNumber: 'MED-2026-003',
    name: 'Arun Iyer',
    age: 34,
    gender: 'MALE',
    phone: '+91 98333 44556',
    email: 'arun.iyer@outlook.com',
    bloodGroup: 'A+',
    address: '12 Koramangala 4th Block, Bangalore',
    allergies: 'Sulfa drugs',
    registeredDate: '2026-03-01',
  },
  {
    id: 4,
    patientNumber: 'MED-2026-004',
    name: 'Sunita Rao',
    age: 29,
    gender: 'FEMALE',
    phone: '+91 98444 55667',
    email: 'sunita.rao@gmail.com',
    bloodGroup: 'AB+',
    address: '108 Jayanagar 9th Block, Bangalore',
    allergies: 'None',
    registeredDate: '2026-04-12',
  },
  {
    id: 5,
    patientNumber: 'MED-2026-005',
    name: 'Kavita Patel',
    age: 71,
    gender: 'FEMALE',
    phone: '+91 98555 66778',
    email: 'kavitap@gmail.com',
    bloodGroup: 'O-',
    address: '55 Whitefield Main Rd, Bangalore',
    allergies: 'Aspirin',
    registeredDate: '2026-05-20',
  },
];

export const initialAvailability = [
  {
    doctorId: 1,
    workingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    shiftStart: '09:00',
    shiftEnd: '17:00',
    breakStart: '13:00',
    breakEnd: '14:00',
    slotDurationMinutes: 30,
    leaves: [
      { id: 101, date: '2026-10-02', reason: 'National Holiday' },
      { id: 102, date: '2026-10-15', reason: 'Medical Conference' },
    ],
  },
  {
    doctorId: 2,
    workingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Saturday'],
    shiftStart: '09:30',
    shiftEnd: '16:30',
    breakStart: '13:00',
    breakEnd: '14:00',
    slotDurationMinutes: 30,
    leaves: [],
  },
  {
    doctorId: 3,
    workingDays: ['Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    shiftStart: '10:00',
    shiftEnd: '16:00',
    breakStart: '13:00',
    breakEnd: '13:45',
    slotDurationMinutes: 45,
    leaves: [],
  },
  {
    doctorId: 4,
    workingDays: ['Monday', 'Tuesday', 'Wednesday', 'Friday', 'Saturday'],
    shiftStart: '09:00',
    shiftEnd: '15:00',
    breakStart: '12:30',
    breakEnd: '13:30',
    slotDurationMinutes: 20,
    leaves: [],
  },
  {
    doctorId: 5,
    workingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    shiftStart: '08:30',
    shiftEnd: '16:30',
    breakStart: '13:00',
    breakEnd: '14:00',
    slotDurationMinutes: 15,
    leaves: [],
  },
];

export const initialAppointments = [
  {
    id: 1001,
    patientId: 1,
    patientName: 'Ramesh Kumar',
    patientNumber: 'MED-2026-001',
    doctorId: 1,
    doctorName: 'Dr. Priya Sharma',
    departmentId: 1,
    departmentName: 'Cardiology',
    appointmentDate: new Date().toISOString().split('T')[0],
    appointmentTime: '10:00 AM',
    type: 'CONSULTATION',
    priority: 'NORMAL',
    status: 'IN_CONSULTATION',
    notes: 'Follow-up for hypertension',
    tokenNumber: 'CARD-101',
  },
  {
    id: 1002,
    patientId: 2,
    patientName: 'Meena Devi',
    patientNumber: 'MED-2026-002',
    doctorId: 1,
    doctorName: 'Dr. Priya Sharma',
    departmentId: 1,
    departmentName: 'Cardiology',
    appointmentDate: new Date().toISOString().split('T')[0],
    appointmentTime: '10:30 AM',
    type: 'EMERGENCY',
    priority: 'EMERGENCY',
    status: 'WAITING',
    notes: 'Severe chest discomfort and palpitations',
    tokenNumber: 'CARD-E01',
  },
  {
    id: 1003,
    patientId: 3,
    patientName: 'Arun Iyer',
    patientNumber: 'MED-2026-003',
    doctorId: 2,
    doctorName: 'Dr. Arvind Patel',
    departmentId: 2,
    departmentName: 'Orthopedics',
    appointmentDate: new Date().toISOString().split('T')[0],
    appointmentTime: '11:00 AM',
    type: 'ROUTINE',
    priority: 'NORMAL',
    status: 'WAITING',
    notes: 'Right knee joint pain',
    tokenNumber: 'ORTH-102',
  },
  {
    id: 1004,
    patientId: 4,
    patientName: 'Sunita Rao',
    patientNumber: 'MED-2026-004',
    doctorId: 4,
    doctorName: 'Dr. Ananya Sen',
    departmentId: 4,
    departmentName: 'Pediatrics',
    appointmentDate: new Date().toISOString().split('T')[0],
    appointmentTime: '11:30 AM',
    type: 'FOLLOW_UP',
    priority: 'NORMAL',
    status: 'SCHEDULED',
    notes: 'Child routine immunization check',
    tokenNumber: 'PEDI-103',
  },
  {
    id: 1005,
    patientId: 5,
    patientName: 'Kavita Patel',
    patientNumber: 'MED-2026-005',
    doctorId: 1,
    doctorName: 'Dr. Priya Sharma',
    departmentId: 1,
    departmentName: 'Cardiology',
    appointmentDate: new Date().toISOString().split('T')[0],
    appointmentTime: '12:00 PM',
    type: 'CONSULTATION',
    priority: 'SENIOR_CITIZEN',
    status: 'WAITING',
    notes: 'ECG review for elderly patient',
    tokenNumber: 'CARD-S02',
  },
];

export const initialQueue = [
  {
    id: 501,
    appointmentId: 1001,
    tokenNumber: 'CARD-101',
    patientName: 'Ramesh Kumar',
    patientNumber: 'MED-2026-001',
    doctorName: 'Dr. Priya Sharma',
    departmentName: 'Cardiology',
    position: 0,
    priority: 'NORMAL',
    priorityReason: 'Regular Consultation',
    status: 'IN_CONSULTATION',
    patientsAhead: 0,
    estimatedWaitMinutes: 0,
    checkedInTime: '09:45 AM',
  },
  {
    id: 502,
    appointmentId: 1002,
    tokenNumber: 'CARD-E01',
    patientName: 'Meena Devi',
    patientNumber: 'MED-2026-002',
    doctorName: 'Dr. Priya Sharma',
    departmentName: 'Cardiology',
    position: 1,
    priority: 'EMERGENCY',
    priorityReason: 'Acute Chest Discomfort - Triage Priority 1',
    status: 'WAITING',
    patientsAhead: 0,
    estimatedWaitMinutes: 5,
    checkedInTime: '09:50 AM',
  },
  {
    id: 503,
    appointmentId: 1005,
    tokenNumber: 'CARD-S02',
    patientName: 'Kavita Patel',
    patientNumber: 'MED-2026-005',
    doctorName: 'Dr. Priya Sharma',
    departmentName: 'Cardiology',
    position: 2,
    priority: 'SENIOR_CITIZEN',
    priorityReason: 'Senior Citizen (>70 years) Priority Policy',
    status: 'WAITING',
    patientsAhead: 1,
    estimatedWaitMinutes: 25,
    checkedInTime: '10:05 AM',
  },
  {
    id: 504,
    appointmentId: 1003,
    tokenNumber: 'ORTH-102',
    patientName: 'Arun Iyer',
    patientNumber: 'MED-2026-003',
    doctorName: 'Dr. Arvind Patel',
    departmentName: 'Orthopedics',
    position: 1,
    priority: 'NORMAL',
    priorityReason: 'Scheduled Consultation',
    status: 'WAITING',
    patientsAhead: 0,
    estimatedWaitMinutes: 10,
    checkedInTime: '10:15 AM',
  },
];

export const initialAuditLogs = [
  {
    id: 9001,
    timestamp: '2026-09-22 09:15:22',
    user: 'receptionist (Sarah Jenkins)',
    action: 'REGISTER_PATIENT',
    entity: 'Patient',
    entityId: 'MED-2026-005',
    details: 'Registered patient Kavita Patel, age 71',
  },
  {
    id: 9002,
    timestamp: '2026-09-22 09:20:04',
    user: 'receptionist (Sarah Jenkins)',
    action: 'BOOK_APPOINTMENT',
    entity: 'Appointment',
    entityId: '1005',
    details: 'Booked appointment with Dr. Priya Sharma for Kavita Patel',
  },
  {
    id: 9003,
    timestamp: '2026-09-22 09:21:40',
    user: 'system (QueueEngine)',
    action: 'PRIORITY_EVALUATE',
    entity: 'QueueToken',
    entityId: 'CARD-S02',
    details: 'Assigned Senior Citizen priority based on age >= 70',
  },
  {
    id: 9004,
    timestamp: '2026-09-22 09:45:10',
    user: 'doctor (Dr. Priya Sharma)',
    action: 'START_CONSULTATION',
    entity: 'QueueToken',
    entityId: 'CARD-101',
    details: 'Started consultation for Ramesh Kumar in OPD-102',
  },
  {
    id: 9005,
    timestamp: '2026-09-22 09:51:30',
    user: 'receptionist (Sarah Jenkins)',
    action: 'EMERGENCY_OVERRIDE',
    entity: 'QueueToken',
    entityId: 'CARD-E01',
    details: 'Triaged Meena Devi as Emergency due to acute cardiac symptoms',
  },
];
